# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunSQL('''
        
    CREATE TABLE "admin" (
        "id" INT NOT NULL,
        "login" VARCHAR2(255) UNIQUE NOT NULL,
        "password" VARCHAR2(255) NOT NULL,
        constraint ADMIN_PK PRIMARY KEY ("id"));
        
        '''),
]
