# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0001'),
    ]

    operations = [
        migrations.RunSQL('''
    
    CREATE TABLE "customer" (
        "id" INT NOT NULL,
        "email" VARCHAR2(255) UNIQUE NOT NULL check
         ( "email" LIKE '%@%.%'),
        "password" VARCHAR2(255) NOT NULL,
        constraint CUSTOMER_PK PRIMARY KEY ("id"));
    
        '''),
    ]
