# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002'),
    ]

    operations = [
        migrations.RunSQL('''
    
    CREATE TABLE "category" (
        "id" INT NOT NULL,
        "title" VARCHAR2(255) NOT NULL,
        "description" VARCHAR2(255) NOT NULL,
        constraint CATEGORY_PK PRIMARY KEY ("id"));
    
    '''),
    ]
