# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0003'),
    ]

    operations = [
        migrations.RunSQL('''
    
    CREATE TABLE "product" (
        "id" INT NOT NULL,
        "name" VARCHAR2(50) NOT NULL,
        "count" INT NOT NULL,
        "price" FLOAT NOT NULL,
        "photo" VARCHAR2(255),
        "category_id" INT NOT NULL,
        constraint PRODUCT_PK PRIMARY KEY ("id"));
    
    '''),
    ]
