# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004'),
    ]

    operations = [
        migrations.RunSQL(''' 
    
    CREATE TABLE "cart" (
        "id" INT NOT NULL,
        "purchase_id" INT NOT NULL,
        "customer_id" INT NOT NULL,
        constraint CART_PK PRIMARY KEY ("id"));
    
    '''),
    ]
