# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005'),
    ]

    operations = [
        migrations.RunSQL('''
    
    CREATE TABLE "cart_content" (
        "id" INT NOT NULL,
        "count" INT NOT NULL,
        "product_id" INT NOT NULL,
        "cart_id" INT NOT NULL,
        constraint CART_CONTENT_PK PRIMARY KEY ("id"));
    
    '''),
    ]
