# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0006'),
    ]

    operations = [
        migrations.RunSQL('''
    
    CREATE TABLE "purchase" (
        "id" INT NOT NULL,
        "date" TIMESTAMP NOT NULL,
        "total_price" FLOAT NOT NULL,
        constraint PURCHASE_PK PRIMARY KEY ("id"));
    
    '''),
    ]
