# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0008'),
    ]

    operations = [
        migrations.RunSQL('''
    
    CREATE TABLE "customer_address" (
        "id" INT NOT NULL,
        "address" VARCHAR2(255) NOT NULL,
        "customer_id" INT NOT NULL,
        constraint CUSTOMER_ADDRESS_PK PRIMARY KEY ("id"));
    
   '''),
    ]
