# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0009'),
    ]

    operations = [
        migrations.RunSQL('''
    
    ALTER TABLE "product" ADD CONSTRAINT "product_fk0" FOREIGN KEY ("category_id") REFERENCES "category"("id");
    ALTER TABLE "cart" ADD CONSTRAINT "cart_fk0" FOREIGN KEY ("purchase_id") REFERENCES "purchase"("id");
    ALTER TABLE "cart" ADD CONSTRAINT "cart_fk1" FOREIGN KEY ("customer_id") REFERENCES "customer"("id");
    ALTER TABLE "cart_content" ADD CONSTRAINT "cart_content_fk0" FOREIGN KEY ("product_id") REFERENCES "product"("id");
    ALTER TABLE "cart_content" ADD CONSTRAINT "cart_content_fk1" FOREIGN KEY ("cart_id") REFERENCES "cart"("id");
    ALTER TABLE "customer_phone" ADD CONSTRAINT "customer_phone_fk0" FOREIGN KEY ("customer_id") REFERENCES "customer"("id");
    ALTER TABLE "customer_address" ADD CONSTRAINT "customer_address_fk0" FOREIGN KEY ("customer_id") REFERENCES "customer"("id");

        '''),
    ]
