# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0010'),
    ]

    operations = [
        migrations.RunSQL('''
        
            insert into "admin" ("id", "login", "password") values ('1', 'admin', '12345');
            
            insert into "category" ("id", "title", "description") values ('1', 'Laptop', 'Laptop'); 
            insert into "category" ("id", "title", "description") values ('2', 'PC', 'PC');
            insert into "category" ("id", "title", "description") values ('3', 'Monitor', 'Monitor');
            
            insert into "product" ("id", "name", "count", "price", "photo", "category_id") values ('1', 'Acer Laptop', 11, 200000, 'images/laptop.png', 1);
            insert into "product" ("id", "name", "count", "price", "photo", "category_id") values ('2', 'Asus Laptop', 4, 400000, 'images/laptop.png', 1);
            insert into "product" ("id", "name", "count", "price", "photo", "category_id") values ('3', 'Asus PC', 3, 800000, 'images/pc.png', 2);
            insert into "product" ("id", "name", "count", "price", "photo", "category_id") values ('4', 'Lenovo PC', 7, 700000, 'images/pc.png', 2);
            insert into "product" ("id", "name", "count", "price", "photo", "category_id") values ('5', 'Lg Monitor', 2, 60000, 'images/monitor.png', 3);
            insert into "product" ("id", "name", "count", "price", "photo", "category_id") values ('6', 'Samsung Monitor', 5, 80000, 'images/monitor.png', 3);
            
        '''),
    ]
